# magnum build helpers. launchd runs bin/magnum through `mise exec` (see `magnum install`).

GO            ?= go
BIN           ?= bin/magnum
VERSION       ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
INSTALL_FLAGS ?= --plugin

.PHONY: build test check-private install api-doc

## build: compile bin/magnum (the binary launchd and the herdr plugin run)
build:
	$(GO) build -ldflags "-X main.version=$(VERSION)" -o $(BIN) ./cmd/magnum

## test: gofmt check, vet, the hermetic unit tests, and the private-name guard
test: check-private
	@out="$$(gofmt -l cmd internal)"; if [ -n "$$out" ]; then echo "gofmt needed:"; echo "$$out"; exit 1; fi
	$(GO) vet ./...
	$(GO) test ./...

## check-private: this repo is public; fail when a tracked file mentions a name listed in MAGNUM_PRIVATE_PATTERNS
## (a grep -E pattern set in the gitignored .mise.local.toml, never in a tracked file), or a person's GitHub
## login from the local registry (scripts/check-logins.sh; MAGNUM_OWN_LOGINS and MAGNUM_LOGIN_ALLOW exempt)
check-private:
	@if [ -n "$$MAGNUM_PRIVATE_PATTERNS" ] && git grep -qiIE -e "$$MAGNUM_PRIVATE_PATTERNS" -- . ':!config.local.toml'; then \
	  echo "tracked files mention a private name:"; git grep -niIE -e "$$MAGNUM_PRIVATE_PATTERNS" -- . ':!config.local.toml'; exit 1; fi
	@scripts/check-logins.sh

## install: build, then load the launchd agent and link the herdr plugin (INSTALL_FLAGS="" skips the plugin)
install: build
	$(BIN) install $(INSTALL_FLAGS)

## api-doc: regenerate the package sections of docs/API.md from `go doc -all` (the hand-written text above the marker is kept)
API_MARKER := <!-- generated by `make api-doc` below this line; edit only the text above -->
api-doc:
	@grep -qF '$(API_MARKER)' docs/API.md || { echo "docs/API.md: marker line missing"; exit 1; }
	@{ sed -n '1,/^<!-- generated by `make api-doc`/p' docs/API.md; \
	  echo; echo '| Package | Synopsis |'; echo '|---|---|'; \
	  $(GO) list -f '| [{{.Name}}](#{{.Name}}) | {{.Doc}} |' ./internal/...; \
	  for p in $$($(GO) list -f '{{.Name}}' ./internal/...); do \
	    echo; echo "## $$p"; echo; echo '```text'; $(GO) doc -all ./internal/$$p || exit 1; echo '```'; \
	  done; } > docs/API.md.tmp && mv docs/API.md.tmp docs/API.md
	@echo "docs/API.md regenerated"
