# magnum build helpers. `make install` loads the launchd agent for bin/magnum (see `magnum install`);
# `make release VERSION=vX.Y.Z` tags, publishes and updates the Homebrew tap (scripts/release.sh).

GO            ?= go
GOLANGCI_LINT ?= golangci-lint
BIN           ?= bin/magnum
VERSION       ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
INSTALL_FLAGS ?= --plugin

.PHONY: build test check-private lint lint-fix vuln install api-doc api-doc-check release link unlink

## build: compile bin/magnum (the binary launchd and the herdr plugin run)
build:
	$(GO) build -ldflags "-X main.version=$(VERSION)" -o $(BIN) ./cmd/magnum

## test: gofmt check (every tracked .go file, and new ones git does not ignore), go.sum verified and go.mod tidy,
## vet, the hermetic unit tests, and the private-name guard
test: check-private
	@out="$$(git ls-files -z --cached --others --exclude-standard '*.go' | xargs -0 gofmt -l)"; if [ -n "$$out" ]; then echo "gofmt needed:"; echo "$$out"; exit 1; fi
	$(GO) mod verify
	$(GO) mod tidy -diff
	$(GO) vet ./...
	$(GO) test ./...

## check-private: this repo is public; fail when a tracked file mentions a name listed in MAGNUM_PRIVATE_PATTERNS
## (a grep -E pattern set in the gitignored .mise.local.toml, never in a tracked file), or a person's GitHub
## login from the local registry (scripts/check-logins.sh; MAGNUM_OWN_LOGINS and MAGNUM_LOGIN_ALLOW exempt)
check-private:
	@if [ -n "$$MAGNUM_PRIVATE_PATTERNS" ] && git grep -qiIE -e "$$MAGNUM_PRIVATE_PATTERNS" -- . ':!config.local.toml'; then \
	  echo "tracked files mention a private name:"; git grep -niIE -e "$$MAGNUM_PRIVATE_PATTERNS" -- . ':!config.local.toml'; exit 1; fi
	@scripts/check-logins.sh

## lint: golangci-lint with .golangci.yml (the version .mise.toml pins); not part of `test` until the backlog is cleared
lint:
	$(GOLANGCI_LINT) run ./...

## lint-fix: apply only the safe automatic fixes (modernize, intrange), then the formatters; never a blanket --fix
## (errorlint's fix for internal/pipeline/restart.go breaks the build). The fix pass fails while it leaves hits it
## cannot fix (a range over a method's result), so its status is ignored and the formatters still run.
lint-fix:
	-$(GOLANGCI_LINT) run --fix --enable-only modernize,intrange ./...
	$(GOLANGCI_LINT) fmt ./...

## vuln: govulncheck: known vulnerabilities the code reaches, in its dependencies and in the Go release it builds with
vuln:
	$(GO) run golang.org/x/vuln/cmd/govulncheck@v1.8.0 ./...

## install: build, then load the launchd agent and link the herdr plugin (INSTALL_FLAGS="" skips the plugin)
install: build
	$(BIN) install $(INSTALL_FLAGS)

## api-doc: regenerate the package sections of docs/API.md from `go doc -all` (the hand-written text above the marker is kept;
## API_DOC_OUT=<file> writes the result there instead, which api-doc-check uses)
API_MARKER  := <!-- generated by `make api-doc` below this line; edit only the text above -->
API_DOC_OUT  = docs/API.md
api-doc:
	@grep -qF '$(API_MARKER)' docs/API.md || { echo "docs/API.md: marker line missing"; exit 1; }
	@{ sed -n '1,/^<!-- generated by `make api-doc`/p' docs/API.md; \
	  echo; echo '| Package | Synopsis |'; echo '|---|---|'; \
	  $(GO) list -f '| [{{.Name}}](#{{.Name}}) | {{.Doc}} |' ./internal/...; \
	  for d in $$($(GO) list -f '{{.ImportPath}}' ./internal/...); do \
	    echo; echo "## $${d##*/}"; echo; echo '```text'; $(GO) doc -all $$d || exit 1; echo '```'; \
	  done; } > $(API_DOC_OUT).tmp && mv $(API_DOC_OUT).tmp $(API_DOC_OUT)
	@[ "$(API_DOC_OUT)" != docs/API.md ] || echo "docs/API.md regenerated"

## api-doc-check: fail when docs/API.md differs from what `make api-doc` writes (generated into a temporary file, diffed)
api-doc-check:
	@tmp="$$(mktemp -d)" && trap 'rm -rf "$$tmp"' EXIT && \
	  $(MAKE) --no-print-directory -s api-doc API_DOC_OUT="$$tmp/API.md" && \
	  { diff -u docs/API.md "$$tmp/API.md" || { echo "docs/API.md is stale: run make api-doc and commit it"; exit 1; }; }

## release: tag the pushed master as $(VERSION) (vX.Y.Z), publish the GitHub release, update the Homebrew tap
release:
	scripts/release.sh $(VERSION)

## link: put this checkout's build on PATH as ~/.local/bin/magnum (a symlink, so every `make build` updates it)
link: build
	@mkdir -p $(HOME)/.local/bin
	@ln -sfn $(CURDIR)/$(BIN) $(HOME)/.local/bin/magnum
	@echo "~/.local/bin/magnum -> $(CURDIR)/$(BIN)"

## unlink: remove ~/.local/bin/magnum when it is this checkout's link
unlink:
	@if [ "$$(readlink $(HOME)/.local/bin/magnum)" = "$(CURDIR)/$(BIN)" ]; then rm $(HOME)/.local/bin/magnum && echo "removed ~/.local/bin/magnum"; \
	else echo "~/.local/bin/magnum is not this checkout's link; left alone"; fi
